# EI_CLASSIFICATION_MODEL = path to the model file
# CUSTOM_MODEL_PATH = path to the custom model directory
services:
  ei-classification-runner:
    image: ${DOCKER_REGISTRY_BASE:-ghcr.io/bcmi-labs/}arduino/appslab-ei-models-runner:0.2.0
    restart: on-failure
    ports:
      - ${BIND_ADDRESS:-127.0.0.1}:${BIND_PORT:-1337}:1337
    volumes:
      - "${CUSTOM_MODEL_PATH:-/home/arduino/.arduino-bricks/ei-models}:${CUSTOM_MODEL_PATH:-/models/custom/ei/}"
    command: ["--model-file", "${EI_CLASSIFICATION_MODEL:-/models/ootb/ei/mobilenet-v2-224px.eim}", "--run-http-server", "1337", "--dont-print-predictions"]
