#!/bin/sh

set -e

APP_USER="arduino"
APP_GROUP="arduino"
SYSUPGRADE_GROUP="sysupgrade"

if ! getent group "$APP_GROUP" >/dev/null 2>&1; then
    addgroup "$APP_GROUP"
fi

if ! getent passwd "$APP_USER" >/dev/null 2>&1; then
    adduser \
        --ingroup "$APP_GROUP" \
        --home "/home/$APP_USER" \
        --shell /bin/false \
        --disabled-password \
        "$APP_USER" >/dev/null
fi

if ! getent group "$SYSUPGRADE_GROUP" >/dev/null 2>&1; then
    groupadd --system "$SYSUPGRADE_GROUP"
fi
usermod -aG "$SYSUPGRADE_GROUP" "$APP_USER"
